apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sec-user
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-user
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-admin
  namespace: kube-system